### ISSUE TITLE
I believe labels_all.npy is wrong

### ISSUE THREAD

**Issue by kylemin** [sujoyp/wtalc-pytorch#11]
For example, labels[226] has multiple segments of 'HammerThrow', but labels_all[226] is empty even if they indicate the same video.
There are some other examples (238, 242, ...)

How did you get labels_all.npy?

**Comment by sujoyp** [comment]
@kylemin We have temporal information only for the ~400 videos of THUMOS14. We can get the video-level labels from the temporal labels itself, but only for these 400 videos (i.e., THUMOS14Reduced) and not for the entire THUMOS14 dataset. That is the reason, we used the video-level metadata information from  https://www.crcv.ucf.edu/THUMOS14/download.html to obtain the video level labels. However, we do note that there are some errors (very few, as you pointed out) in the annotations that come with the dataset and for a fair comparison with baselines, we stick to them.
