### ISSUE TITLE
difference between labels.npy and labels_all.npy

### ISSUE THREAD

**Issue by dingdongx2** [sujoyp/wtalc-pytorch#13]
Hi. `labels.npy` is called only at `detectionMAP.py` as `gtlabels` and `labels_all.npy` at `video_dataset.py` as `labels`.
At first time, I thought `labels_all.npy` means set of `labels.npy` but when I compare 2 files with same index, it show different results.
Then what's difference between labels.npy and labels_all.npy?

**Comment by sujoyp** [comment]
labels.npy contain the segment level labels of the videos. labels_all.npy contains the video-level labels. We obtain them from here:
https://www.crcv.ucf.edu/THUMOS14/download.html 
labels_all.npy: mentioned as **Metadata and class-level annotations**
labels.npy: mentioned as **Temporal annotations of actions**
