### ISSUE TITLE
Both Classification and Localization Performance is higher in my experiment than your eccv18 paper in Thumos14

### ISSUE THREAD

**Issue by June01** [sujoyp/wtalc-pytorch#14]
Hi @sujoyp,

Thanks for sharing this code! It is quite easy to hand on. I have a minor question:

I have settled down this code in my machine for thumos14reduced. While running, the best performance echoed on the screen in terms of classification map is 96.56%, and localization map@0.5 is 23.67%. However, in your paper, it is 85.6% and 22.8% respectively. I got confused about the difference, could you please help? Thanks in advance.

**Comment by sujoyp** [comment]
Note that the classification performance you obtain when using Thumos14reduced is on the reduced dataset (200 data points for 20 categories). Whereas the numbers mentioned in paper is for the entire dataset, which is Thumos14. It is true that the localization performance obtained using this code is a bit higher than reported in the paper, and we obtained this after some code cleaning.

**Comment by June01** [comment]
Hi sujoyp,

Thanks for your answer. I have another question if I may ask. Is there any reason you write the evaluation code on your own rather than using the official one simply? Have you tested on the official thumos14 matlab code? How is the performance? I am quite curious about it and too lazy to check it on my own. Thanks again!

**Comment by sujoyp** [comment]
We did try the official evaluation repo (which is in Matlab) and found the same results as our python implementation.

**Comment by June01** [comment]
Hi @sujoyp, I see! Thanks for it!
