### ISSUE TITLE
calculate features

### ISSUE THREAD

**Issue by 123liluky** [sujoyp/wtalc-pytorch#5]
How can I calculate UNT or I3D features for my own video datasets?

**Comment by sujoyp** [comment]
You can extract it using the repos [here](https://github.com/deepmind/kinetics-i3d) and [here](https://github.com/wanglimin/UntrimmedNet).

**Comment by 123liluky** [comment]
Using https://github.com/deepmind/kinetics-i3d, I extracted I3D features of a video with size (1,2048). The feature I extracted generated from the last avg_pool3d layer.
![image](https://user-images.githubusercontent.com/20832778/60253050-fa009200-98fd-11e9-8bcf-ae5c55f28b8c.png)
But the video contains 200 frames. So How can I extract features with size (num_frames,2048) like yours? Thank you.

**Comment by Zhuysheng** [comment]
@123liluky  do you solve it?

**Comment by 123liluky** [comment]
In paper, it is written
![1562550078(1)](https://user-images.githubusercontent.com/20832778/60777448-181f8b00-a165-11e9-9956-519107dafbe7.png)
So, we should seperate videos into several parts. Then we can exract features with size (1,2048) for each part.

**Comment by sujoyp** [comment]
@123liluky we first divided the video into non-overlapping chunks of 16 frames and then extracted features for each of these 16 frame chunks. So if you have a video with 201 frames then you should get a feature matrix of dimension (12, 2048).

**Comment by naraysa** [comment]
@sujoyp Wanted to know how the resizing and cropping is done to get 224x224 size for different resolutions of videos. Are multiple random crops obtained and their features averaged per segment?

**Comment by sujoyp** [comment]
@naraysa The entire image is resized to 224x224 without any random cropping.

**Comment by naraysa** [comment]
So, a 180x320 image size is resized directly to 224x224 without any padding or retaining original aspect ratio?

**Comment by sujoyp** [comment]
@naraysa Yes, that is what we did! But any form of data augmentation should turn out to work better, but we did not explore it.

**Comment by naraysa** [comment]
Oh cool. Thanks

**Comment by naraysa** [comment]
@sujoyp Which optical flow implementation did you use? Also, was this image resizing done before optical flow calculation?

**Comment by sujoyp** [comment]
We used the optical flow extraction code from [here](https://github.com/yjxiong/temporal-segment-networks/blob/master/scripts/extract_optical_flow.sh)
Yes, we first resized the images to 224x224 and then extracted the flows.

**Comment by arnavc1712** [comment]
Hi @sujoyp , would the output of the optical flow be (num_frames, 224, 224, 2) ? Or do we have to sample the frames at a desired fps and then calculate optical flow for them?
