### ISSUE TITLE
extracted_fps of Thumos14reduced-I3D-JOINTFeatures

### ISSUE THREAD

**Issue by bfshi** [sujoyp/wtalc-pytorch#9]
Hi! Congratulations to your great work!

I've got some trouble with the extracted_fps.

In the file extracted_fps.npy, it's recorded that frames of each video is extracted at 10 fps. 

However, i find that this does not match the temporal dimension of feature.

For every video, duration * extracted_fps / 16 = feature.shape[0].
Using this equation, I find that every video is extracted at about 25 fps.

Is there something wrong? Did I make any mistake? I cannot find the reason...

**Comment by sujoyp** [comment]
Please ignore the extracted_fps.npy file. 

For I3D, we extract the video frames at 25fps and then extract a single feature vector for every 16 frame input to the network. We do the same thing for both the RGB and FLOW stream. 

For UNT, we extract the video frames at 10 fps and then extract features for every frame (for flow it is a bit different and the input are 5 neighboring frames for every timestamp we want to extract the features). Then we pool 4 such features (non-overlapping) to get a single feature vector, which is then fed as input to our network (i.e., how the 2.5 features come from 10/4=2.5)

**Comment by bfshi** [comment]
Thank you for the detailed reply! That totally solved my confusion!

**Comment by zfhxi** [comment]
Hello, I'm a newer, could you tell me that how to change the fps from 30 to 25 for each video? Should I need drop the frames whose index%6==0 ?
